name       : sassc
version    : 3.5.0
release    : 7
source     :
    - https://github.com/sass/sassc/archive/3.5.0.tar.gz : 26f54e31924b83dd706bc77df5f8f5553a84d51365f0e3c566df8de027918042
license    : MIT
component  : programming.tools
summary    : SassC is a wrapper around libsass used to generate a useful command-line
    application that can be installed and packaged for several operating systems.
description: |
    SassC is a wrapper around libsass used to generate a useful command-line application that can be installed and packaged for several operating systems.
builddeps  :
    - pkgconfig(libsass)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
