name       : sassc
version    : 3.4.5
release    : 3
source     :
    - https://github.com/sass/sassc/archive/3.4.5.tar.gz : 29ea67ebeebb224feb7b0a7d76654f4868804150f8723da8d2e9c7bf6b9d64f6
license    : MIT
component  : programming.tools
summary    : SassC is a wrapper around libsass used to generate a useful command-line application that can be installed and packaged for several operating systems.
description: |
    SassC is a wrapper around libsass used to generate a useful command-line application that can be installed and packaged for several operating systems.
builddeps  :
    - pkgconfig(libsass)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
