name       : sassc
version    : 3.4.8
release    : 4
source     :
    - https://github.com/sass/sassc/archive/3.4.8.tar.gz : 611da54f9d8892bc6cab65bb960c5d192cd1c06d2b80bfe1fcec7d43f38a960a
license    : MIT
component  : programming.tools
summary    : SassC is a wrapper around libsass used to generate a useful command-line application that can be installed and packaged for several operating systems.
description: |
    SassC is a wrapper around libsass used to generate a useful command-line application that can be installed and packaged for several operating systems.
builddeps  :
    - pkgconfig(libsass)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
