name       : sassc
version    : 3.3.6
release    : 1
source     :
    - https://github.com/sass/sassc/archive/3.3.6.tar.gz : 3d87edeacdd0f9a21cd0bdcf0e0e40c832b21f469af80eb5e11488c66bf53840
license    : MIT
component  : programming
summary    : SassC is a wrapper around libsass used to generate a useful command-line application that can be installed and packaged for several operating systems.
description: |
    SassC is a wrapper around libsass used to generate a useful command-line application that can be installed and packaged for several operating systems.
rundeps    :
    - libsass
setup      : |
    autoreconf -vfi
    %configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    install -D -m 0644 LICENSE $installdir/usr/share/licenses/sassc/LICENSE
