name       : sassc
version    : 3.3.6
release    : 1
source     :
    - https://github.com/sass/sassc/archive/3.3.6.tar.gz : 3d87edeacdd0f9a21cd0bdcf0e0e40c832b21f469af80eb5e11488c66bf53840
license    : MIT
component  : programming.tools
summary    : SassC is a wrapper around libsass used to generate a useful command-line application that can be installed and packaged for several operating systems.
description: |
    SassC is a wrapper around libsass used to generate a useful command-line application that can be installed and packaged for several operating systems.
builddeps  :
    - pkgconfig(libsass)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
